language: python
python:
  - "3.6"
script:
  - ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: build
  fqdn: pdf.tsing.net
