language: node_js
node_js:
  - '12'
sudo: false
env:
  - PRODUCTION=1
cache:
  directories:
  - pdf.js/node_modules
install:
  - npm install -g gulp-cli
  - pip install -r requirements.txt
  - pushd . && cd pdf.js
  - npm install
  - gulp minified
  - popd
script:
  - ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: build
  fqdn: pdf.tsing.net
